# Generated by Django 5.0 on 2023-12-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendApp', '0001_initial'),
    ]

    operations = [
    ]
